const products = [
  { name: "এন্টি শ্যাম্পু ১২০", price: 125.0, category: "Shampoo" },
  { name: "এন্টি শ্যাম্পু ৬৫", price: 80.0, category: "Shampoo" },
  { name: "লাইম শ্যাম্পু ৫০০", price: 305.0, category: "Shampoo" },
  { name: "লাইম শ্যাম্পু ৩০০", price: 175.0, category: "Shampoo" },
  { name: "লাইম শ্যাম্পু ১৬০", price: 107.0, category: "Shampoo" },
  { name: "লাইম শ্যাম্পু ৯০", price: 65.0, category: "Shampoo" },
  { name: "এগ শ্যাম্পু ৫০০", price: 305.0, category: "Shampoo" },
  { name: "এগ শ্যাম্পু ৩০০", price: 175.0, category: "Shampoo" },
  { name: "এগ শ্যাম্পু ১৬০", price: 107.0, category: "Shampoo" },
  { name: "এগ শ্যাম্পু ৯০", price: 65.0, category: "Shampoo" },
  { name: "বিউটি শ্যাম্পু ৫০০", price: 305.0, category: "Shampoo" },
  { name: "বিউটি শ্যাম্পু ৩০০", price: 175.0, category: "Shampoo" },
  { name: "বিউটি শ্যাম্পু ১৬০", price: 107.0, category: "Shampoo" },
  { name: "বিউটি শ্যাম্পু ৯০", price: 65.0, category: "Shampoo" },
  {
    name: "আফটার শেভ ১০০",
    price: 115.0,
    category: "After Shave & Shaving Cream",
  },
  {
    name: "আফটার শেভ ৪০",
    price: 54.0,
    category: "After Shave & Shaving Cream",
  },
  {
    name: "আফটার শেভ ৫০",
    price: 68.0,
    category: "After Shave & Shaving Cream",
  },
  {
    name: "সোলজার শেভিং ১০০",
    price: 52.0,
    category: "After Shave & Shaving Cream",
  },
  {
    name: "সোলজার শেভিং ৫৫",
    price: 31.0,
    category: "After Shave & Shaving Cream",
  },
  {
    name: "কিউট শেভিং ১০০",
    price: 52.0,
    category: "After Shave & Shaving Cream",
  },
  {
    name: "কিউট শেভিং ৫৫",
    price: 31.0,
    category: "After Shave & Shaving Cream",
  },
  { name: "ফ্লোরাইড ২০০", price: 82.0, category: "Toothpaste" },
  { name: "ফ্লোরাইড ১০০", price: 50.0, category: "Toothpaste" },
  { name: "ফ্লোরাইড ৫০", price: 32.0, category: "Toothpaste" },
  { name: "জেল পেস্ট ১৫০", price: 80.0, category: "Toothpaste" },
  { name: "স্মোকারস ১০০", price: 165.0, category: "Toothpaste" },
  { name: "পুদিনা ২০০", price: 80.0, category: "Toothpaste" },
  { name: "পুদিনা ১০০", price: 49.0, category: "Toothpaste" },
  { name: "পুদিনা ৫০", price: 32.0, category: "Toothpaste" },
  { name: "ফাস্টলেডি বড় ৬০", price: 425.0, category: "Perfume" },
  { name: "ফাস্টলেডি প্রিমিয়ার ৬০", price: 520.0, category: "Perfume" },
  { name: "ফাস্টলেডি ছোট ১৫", price: 155.0, category: "Perfume" },
  { name: "রোমান্স বড় ৬০", price: 425.0, category: "Perfume" },
  { name: "রোমান্স ছোট ১৫", price: 155.0, category: "Perfume" },
  { name: "রোমান্স নিউ ৪৫", price: 350.0, category: "Perfume" },
  { name: "রোমান্স স্প্রে ১৫", price: 202.0, category: "Perfume" },
  { name: "রোমান্স টুইস্ট ৫০", price: 520.0, category: "Perfume" },
  { name: "ফ্যান্টাসি বড় ৬০", price: 415.0, category: "Perfume" },
  { name: "ফ্যান্টাসি স্প্রে ৩৫", price: 330.0, category: "Perfume" },
  { name: "ফ্যান্টাসি ছোট ১৫", price: 143.0, category: "Perfume" },
  { name: "ক্লাসিক বড় ৬০", price: 415.0, category: "Perfume" },
  { name: "ক্লাসিক ছোট ১৫", price: 143.0, category: "Perfume" },
  { name: "জেসমিন পারফিউম", price: 350.0, category: "Perfume" },
  { name: "ব্রটাল পারফিউম", price: 350.0, category: "Perfume" },
  { name: "ওয়ান হেভেন", price: 350.0, category: "Perfume" },
  { name: "বিগ বস বড় ৬০", price: 425.0, category: "Perfume" },
  { name: "বিগ বস ছোট ৩৫", price: 355.0, category: "Perfume" },
  { name: "ইভিনিং পার্টি বড় ৬০", price: 425.0, category: "Perfume" },
  { name: "ইভিনিং পার্টি ছোট ৩৫", price: 355.0, category: "Perfume" },
  { name: "লাভ এন্ড লাভ ৩৫", price: 355.0, category: "Perfume" },
  { name: "হারবাল তেল ৩৩০", price: 330.0, category: "Herbal & Amla Hair Oil" },
  { name: "হারবাল তেল ১৬০", price: 133.0, category: "Herbal & Amla Hair Oil" },
  { name: "হারবাল তেল ৯০", price: 78.0, category: "Herbal & Amla Hair Oil" },
  { name: "আমলা তেল ২২৫", price: 170.0, category: "Herbal & Amla Hair Oil" },
  { name: "আমলা তেল ১১০", price: 84.0, category: "Herbal & Amla Hair Oil" },
  { name: "আমলা তেল ৫৫", price: 50.0, category: "Herbal & Amla Hair Oil" },
  { name: "রিফাইন্ড তেল ৩৩০", price: 240.0, category: "Coconut Hair Oil" },
  { name: "রিফাইন্ড তেল ১৬০", price: 137.0, category: "Coconut Hair Oil" },
  { name: "রিফাইন্ড তেল ৯০", price: 76.0, category: "Coconut Hair Oil" },
  { name: "রিফাইন্ড তেল ৪৫", price: 36.0, category: "Coconut Hair Oil" },
  { name: "কিউট তেল বড় ৩৩০", price: 240.0, category: "Coconut Hair Oil" },
  { name: "কিউট তেল মাঝারি ১৬০", price: 137.0, category: "Coconut Hair Oil" },
  { name: "কিউট তেল ছোট ৯০", price: 76.0, category: "Coconut Hair Oil" },
  { name: "কিউট তেল টুনি ৪৫", price: 36.0, category: "Coconut Hair Oil" },
  { name: "আতর চন্দন ১০", price: 112.0, category: "Attar" },

  { name: "বেমিসাল ১০", price: 220.0, category: "Attar" },
  { name: "মাসকালান্দার ১০", price: 220.0, category: "Attar" },
  { name: "জান্নাতুল ফেরদৌস", price: 67.0, category: "Attar" },
  { name: "জান্নাতুল নাঈম", price: 67.0, category: "Attar" },
  { name: "চন্দন ৫", price: 67.0, category: "Attar" },
  { name: "আতর গোলাপ", price: 67.0, category: "Attar" },
  { name: "বসরাই গোলাপ", price: 67.0, category: "Attar" },
  { name: "বেমিসাল ৫", price: 112.0, category: "Attar" },
  { name: "মাসকালান্দার ৫", price: 112.0, category: "Attar" },
  { name: "নেইল পলিশ রেগুলার", price: 59.0, category: "Nail Polish" },
  { name: "রিমুভার বড় ৬৫", price: 51.0, category: "Nail Polish" },
  { name: "রিমুভার ছোট ৩০", price: 30.0, category: "Nail Polish" },
  { name: "নেইল পলিশ এক্সট্রা সাইন ১০", price: 75.0, category: "Nail Polish" },
  { name: "নেইল এনামেল ১৫", price: 120.0, category: "Nail Polish" },
  { name: "ইন্টারনেশনাল ক্রীম ১৩০", price: 100.0, category: "Cream" },
  { name: "ইন্টারনেশনাল ক্রীম ৮৫", price: 68.0, category: "Cream" },
  { name: "কিউট ফেয়ারনেস ভ্যানিশিং ক্রীম ৭০", price: 60.0, category: "Cream" },
  { name: "কিউট পার্ল স্নো ৫৫", price: 52.0, category: "Cream" },
  { name: "বৌরানি স্নো ৫৫", price: 52.0, category: "Cream" },
  { name: "জেসমিন সাবান ১২৫", price: 57.0, category: "Soap" },
  { name: "জেসমিন সাবান ৭৫", price: 40.0, category: "Soap" },
  { name: "জেসমিন সাবান ৩০", price: 13.0, category: "Soap" },
  { name: "নিম সাবান ১২৫", price: 65.0, category: "Soap" },
  { name: "নিম সাবান ৭৫", price: 44.0, category: "Soap" },
  { name: "রোজ সাবান ১২৫", price: 57.0, category: "Soap" },
  { name: "রোজ সাবান ৭৫", price: 40.0, category: "Soap" },
  { name: "রোজ সাবান ৩০", price: 13.0, category: "Soap" },
  { name: "লেমন সাবান ১২৫", price: 57.0, category: "Soap" },
  { name: "লেমন সাবান ৭৫", price: 40.0, category: "Soap" },
  { name: "লেমন সাবান ৩০", price: 13.0, category: "Soap" },
  { name: "ফ্রেঞ্চ পাউডার ৪০০", price: 170.0, category: "Powder" },
  { name: "ফ্রেঞ্চ পাউডার ২২৫", price: 107.0, category: "Powder" },
  { name: "ফ্রেঞ্চ পাউডার ১২৫", price: 65.0, category: "Powder" },
  { name: "ফ্লাওয়ার ট্যালক ২০০", price: 83.0, category: "Powder" },
  { name: "ফ্লাওয়ার ট্যালক ১০০", price: 49.0, category: "Powder" },
  { name: "২৭ পাউডার ১৮০", price: 102.0, category: "Powder" },
  { name: "২৭ পাউডার ১০০", price: 62.0, category: "Powder" },
  { name: "প্রীকলি পাউডার ১০০", price: 59.0, category: "Powder" },
  { name: "শীতল পরশ পাউডার ১০০", price: 63.0, category: "Powder" },
  { name: "রোমান্স পাউডার ৪০০", price: 170.0, category: "Powder" },
  { name: "রোমান্স পাউডার ২০০", price: 107.0, category: "Powder" },
  { name: "রোমান্স পাউডার ১০০", price: 65.0, category: "Powder" },
  { name: "লা্বনী লাক্সারি পাউডার", price: 45.0, category: "Powder" },
  { name: "লাবণি রোজ পাউডার", price: 45.0, category: "Powder" },
  { name: "লাভ গুডনাইট পাউডার", price: 53.0, category: "Powder" },
  { name: "সান এন্ড শেড পাউডার", price: 61.0, category: "Powder" },
  { name: "বেবি পাউডার ২০০", price: 135.0, category: "Powder" },
    { name: "বেবি পাউডার ১১০", price: 85.0, category: "Powder" },
      { name: "ইন্টার পাউডার ২০০", price: 102.0, category: "Powder" },
        { name: "ইন্টার পাউডার ১০০", price: 56.0, category: "Powder" },
  { name: "ফ্লাওয়ার ট্যালক ১০০", price: 49.0, category: "Other" },
  { name: "ফ্লাওয়ার ট্যালক ২০০", price: 83.0, category: "Other" },
];
